language: objective-c
osx_image: xcode9
env:
  global:
  - APPNAME=PgySDKDemo
  - PROFILE_NAME=sdk_demo
  - DEVELOPER_NAME=iPhone Distribution: shengtao lei (DG37YK9PRK)
  - secure: VE9opXtdtxSYb9rFZflJE9TAki9Sk4Cc/zR430rXh+G1QdopuuojFaPoHDd1La5zL7PbctPfrCY1FesviUh2rGfXfstmOkLZhRhI8dLrAnj/GlqTH5c8TV/HiZZzLUUuvLva7BZ65DLO0f18oxJa7V+YK0kqWZNpMLfm8YhISELTtSUfgTqFgXcvfLHfshuZxWmPs6fRGP20wEQwf52Oh5pdIN+uL3IwfJqt3AusC8P5EpKX7Y4qvUDKC5V5vF2bPkibJkPi8Pgm6utt+5AkxdhCyHjijelc8IU0zUpzoJBi15Ja8zH43CJZg7vK3kyDDMYKoB+W2ll1F4HjWO3SW4pwwOK3Y1SA97hS+x2PUazm/m9xDJILpenMmFJvpCakCz0cFPojmDumb9L5/Eljv9XaZMFbvX3OSa/sQvQxnlr3DYkhpGZJ5A8EmZgHtKnq6kHu0s2gTuNsAexxvieBRbB2JUAHVugS7QE861gKVc0vxByAIUwS1IT2BchdqK6guv8IZ4lJaEXKgG7jlcKV3YeGhtZ3WITPW/GUdGdAhEHUsaLAty4ASFEPNrPgzN1GDHeAgVBw3+5hfINAwc5ci589Umu3gyHhDlaRUlvFOQxE1UzPAF2CLOS2Yy2Zfk+oNbNwHGo5o6vQrWIAC8uUW8D9IrSHk39do+mlc5twO/A=
before_install:
- openssl aes-256-cbc -K $encrypted_3c4b9fb3b43f_key -iv $encrypted_3c4b9fb3b43f_iv
  -in scripts/travis/sdk_demo.cer.enc -out scripts/travis/sdk_demo.cer -d
- openssl aes-256-cbc -K $encrypted_3c4b9fb3b43f_key -iv $encrypted_3c4b9fb3b43f_iv
  -in scripts/travis/sdk_demo.p12.enc -out scripts/travis/sdk_demo.p12 -d
- openssl aes-256-cbc -K $encrypted_3c4b9fb3b43f_key -iv $encrypted_3c4b9fb3b43f_iv
  -in scripts/profile/sdk_demo.mobileprovision.enc -out scripts/profile/sdk_demo.mobileprovision -d
  - chmod +x scripts/travis/add-key.sh
  - chmod +x scripts/travis/remove-key.sh
  - chmod +x scripts/travis/sign-and-upload.sh
before_script:
  - ./scripts/travis/add-key.sh
after_script:
  - ./scripts/travis/remove-key.sh
after_success:
  - ./scripts/travis/sign-and-upload.sh

